services:
  pg:
    build:
      context: .
      dockerfile: Dockerfile.pg
    image: pg-img
    pull_policy: build  # Skip trying to pull, just build
    container_name: pg-cont
    environment:
      POSTGRES_USER: stef
      POSTGRES_PASSWORD: stef
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  spark:
    build:
      context: .
      dockerfile: Dockerfile.spark
      args:
        - REBUILD_TOKEN=${REBUILD_TOKEN:-default}
    image: spark-img
    pull_policy: build  # Skip trying to pull, just build
    container_name: spark-cont
    ports:
      - "7077:7077"
      - "8080:8080"

  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    image: app-img
    pull_policy: build  # Skip trying to pull, just build
    container_name: app-cont
    privileged: true # Needed to drop the caches in run_experiment.sh
    depends_on:
      - pg
      - spark
    volumes:
      - .:/app
    working_dir: /app

volumes:
  pgdata:
